cache:
  - node_modules
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node 8 x64
  - npm i

test: off

for:
-
  branches:
    only:
      - master

  build_script:
    - npm run rdp-ia32-release
    - npm run rdp-x64-release

-
  branches:
    only:
      - beta

  build_script:
    - npm run rdp-ia32-beta
    - npm run rdp-x64-beta

branches:
  only:
    - master
    - beta